version: 2.1

defaults:
  - &base_docker
    - image: circleci/python:3.7
  - &run_always_org_context
    context: org-global
    filters:
      tags:
        only: /.*/
      branches:
        ignore: gh-pages
  - &master_only_org_context
    context: org-global
    filters:
      branches:
        only: master
  - &tag_only_org_context
    context: org-global
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /.*/
  - &tag_and_master_only_org_context
    context: org-global
    filters:
      branches:
        only: master
      tags:
        only: /.*/

jobs:
  lint_python:
    docker: *base_docker
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Linting files with black
          command: |
            pip install black
            black --check .

  build_python_wheel:
    docker: *base_docker
    working_directory: /home/circleci/project/
    steps:
      - checkout:
          path: /home/circleci/project/
      - run:
          name: Building wheel
          command: python setup.py bdist_wheel
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - dist
      - store_artifacts:
          path: /home/circleci/project/dist
          destination: wheel

  push_wheel:
    docker: *base_docker
    steps:
      - attach_workspace:
          at: /home/circleci/
      - run:
          name: Upload Wheel
          command: |
            pip install twine
            twine upload /home/circleci/dist/*

  build_examples:
    docker: *base_docker
    parameters:
      example:
        type: enum
        enum: ["binder_logo", "execute_with_preamble", "no_code"]
        default: "binder_logo"
    working_directory: /home/circleci/project/examples/<<parameters.example>>
    steps:
      - checkout:
          path: /home/circleci/project/
      - restore_cache:
          keys:
            - <<parameters.example>>-deps-1-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install deps
          command: |
            pipenv install
      - save_cache:
          key: <<parameters.example>>-deps-1-{{ checksum "Pipfile.lock" }}
          paths:
            - /home/circleci/.local/share/virtualenvs/
      - run:
          name: Build example
          command: pipenv run mkdocs build
      - store_artifacts:
          path: /home/circleci/project/examples/<<parameters.example>>/site
          destination: <<parameters.example>>

workflows:
  run_build_pipeline:
    jobs:
      - lint_python:
          <<: *run_always_org_context
      - build_python_wheel:
          <<: *run_always_org_context
      - build_examples:
          matrix:
            parameters:
              example: ["binder_logo", "execute_with_preamble", "no_code"]
      - push_wheel:
          requires:
            - lint_python
            - build_python_wheel
            - build_examples
          <<: *tag_and_master_only_org_context
